### ISSUE TITLE
Programmatically and idempotently create monitors 

### ISSUE THREAD

**Issue by rndmh3ro** [BigBoot/AutoKuma#84]
I want to create a new group and monitor via the kuma-cli programatically.

```
kuma-cli --url http://127.0.0.1:3001 --username admin --password "" monitor add test.json
```

where test.json contains:

```
{
  "active": true,
  "name": "foo",
  "parent": null,
  "type": "group"
}
```

This works the first time. Now when I run the same command again, it creates a second group with the same name again. Same goes for monitors.

Now I could add ID's to the group like this:

```
{
  "active": true,
  "name": "foo",
  "parent": null,
  "id": 3,
  "type": "group"
}
```

Then the group is not created a second time.

**This works when there was at least one monitor created by hand before creating a monitor programmatically.**

However when I want to create a new group or monitor if there is none existing, it fails with this error message (coming from kuma, not AutoKuma):

```
{"error":"Server responded with an error: You do not own this monitor."}
```

Here's the upstream-code that is responsible: https://github.com/louislam/uptime-kuma/blob/dd75890364fe9cbdfbef6119da6c126234fa6044/server/server.js#L1646

Another uptime-kuma-cli checks if the monitor already exists (by comparing _only_ the name): https://github.com/devopsforhumans/kumaone/blob/dev/src/kumaone/monitors.py#L84

Are you open to supporting idempotence?

**Comment by BigBoot** [comment]
Hi, 

names in Uptime Kuma are not unique, in fact I have multiple Monitors with the same name due to how I structure my monitors, so this seems like a "bad idea".

The `kuma` CLI was created to be easily scriptable though, that is all outputs are formatted as json and all inputs can be fed from stdin so you can use tools like jq to get the list of existing monitors and then create or delete depending on the existence of a monitor with a specific name and possible package this all in a alias/bash function/script.
